import "@/styles/globals.css";

import { type Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { LiveblocksProviderWrapper } from "@/components/liveblocks-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  // Bricolage is variable, supports axes.
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${bricolage.variable}`}>
      <body>
        <TRPCReactProvider>
          <LiveblocksProviderWrapper>
            {children}
          </LiveblocksProviderWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
