import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Newsreader } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { LiveblocksProviderWrapper } from "@/components/liveblocks-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-newsreader",
  style: "italic", // Newsreader is often used in italic for that "literary" feel, but let's load both normal and italic if possible, or just variable.
  // Variable fonts usually support axes.
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} ${newsreader.variable}`}>
      <body>
        <TRPCReactProvider>
          <LiveblocksProviderWrapper>
            {children}
          </LiveblocksProviderWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
